= API-First Development

*API-first development* is a strategy in which the *first* order of business is to develop an API that puts your target developer’s interests first and *then* build the product on top of it (be it a website, mobile application, or a SaaS software). By building on top of APIs with developers in mind, you and your developers are saving a lot of work while laying down the foundations for others to build on.

== 

----
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.micro",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.2",
    "applicationType": "microservice",
    "baseName": "micro",
    "packageName": "com.example.micro",
    "packageFolder": "com/example/micro",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "entitySuffix": "",
    "otherModules": [],
    "testFrameworks": [],
    "enableTranslation": false,
    "skipClient": true,
    "skipUserManagement": true
  }
}
----

----
    packageFolder": "../../../build/jhipster/com/example/micro",
----
---
jhipster import-jdl src/main/resources/model/jhipster-jdl.jh
---

link:https://www.jhipster.tech/jdl/[Reference JDL]

----
// Entities for Microservice

entity Pet {
    id Long required,
    name String required maxlength(256),
    tag String required maxlength(256),
    type String maxlength(256)
}

entity Order {
    id Long required
}

relationship OneToOne {
  Order{pet(id)} to Pet
}

service * with serviceClass
paginate Pet,Order with pager
----

New columns or modifications upon the previous schema are added inside the first changelog. Because of that some **manual** modifications must be done:

- Remove new column that has been added into the (initial) createTable. In this case liquibase throws an error because of the hash.
- Add new _changeset_ with the new column.
- Remove, if desired the `<!-- jhipster-needle-liquibase-add-column ...` so it will be added within the new element.

----
<!--
    Added the entity Pet.
-->
<changeSet id="20190503125000-1" author="jhipster">
    <createTable tableName="pet">
        <column name="id" type="bigint" autoIncrement="${autoIncrement}">
            <constraints primaryKey="true" nullable="false"/>
        </column>
        <column name="name" type="varchar(256)">
            <constraints nullable="false" />
        </column>
        <column name="tag" type="varchar(256)">
            <constraints nullable="false" />
        </column>
    </createTable>
</changeSet>
<!--
    Added column changeset
-->
<changeSet id="20190503125000-2" author="jhipster">
    <addColumn tableName="pet">

        <column name="type" type="varchar(256)">
            <constraints nullable="true" />
        </column>

        <!-- jhipster-needle-liquibase-add-column - JHipster will add columns here, do not remove-->
    </addColumn>
</changeSet>
----