{
 "title": "Gateway Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Customer Requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "com_logging_request_total{uri=\"/customer\",verb=\"get\"}"
    }
   ]
  },
  {
   "title": "Customer Error",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(com_logging_request_error_total{uri=\"/customer\",verb=\"get\"} / com_logging_request_total{uri=\"/customer\",verb=\"get\"}) "
    }
   ]
  },
  {
   "title": "Order Requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "com_logging_request_total{uri=\"/order\",verb=\"get\"}"
    }
   ]
  },
  {
   "title": "Customer Error",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(com_logging_request_error_total{uri=\"/order\",verb=\"get\"} / com_logging_request_total{uri=\"/order\",verb=\"get\"})"
    }
   ]
  },
  {
   "title": "Time Per Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_logging_request_timing_seconds_max",
     "legendFormat": "{{service}}-{{verb}}{{uri}}"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(com_logging_request_error_total[1m])",
     "legendFormat": "{{service}}-{{verb}}{{uri}}"
    }
   ]
  },
  {
   "title": "Concurrent Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "com_logging_request_gauges", "legendFormat": "{{service}}-{{verb}}{{uri}}" }
   ]
  }
 ]
}