# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
	# Create kubernets Master node
	config.vm.define "k8s-master" do |masterk8sconfig|
		masterk8sconfig.vm.box = "ubuntu/xenial64"
		masterk8sconfig.vm.hostname = "k8s-master"
		masterk8sconfig.vm.network "private_network", ip: "10.0.0.11"
		masterk8sconfig.vm.synced_folder ".", "/vagrant"
		masterk8sconfig.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.name = "k8s-master"
			vb.memory = "2048"
		end
		masterk8sconfig.vm.provision :shell, path: "provision/ubuntu_update.sh"
		masterk8sconfig.vm.provision :shell, path: "provision/java_install.sh"
		masterk8sconfig.vm.provision :shell, path: "provision/docker_install.sh"
		masterk8sconfig.vm.provision :shell, path: "provision/docker_compose_install.sh"
		masterk8sconfig.vm.provision :shell, path: "provision/kubeadm_install.sh"
		masterk8sconfig.vm.provision :shell, path: "provision/addons_install.sh"
		masterk8sconfig.vm.provision :shell, path: "provision/config_k8s_nodes.sh"
		masterk8sconfig.vm.provision :shell, path: "provision/kubeadm-master-init.sh"
	end
  
 	# Create kubernets Workers
	(1..2).each do |i|
		config.vm.define "k8s-node#{i}" do |nodek8sconfig|
			nodek8sconfig.vm.box = "ubuntu/xenial64"
			nodek8sconfig.vm.hostname = "k8s-node#{i}"
			nodek8sconfig.vm.network "private_network", ip: "10.0.0.2#{i}"
			nodek8sconfig.vm.synced_folder ".", "/vagrant"
			nodek8sconfig.vm.provider "virtualbox" do |vb|
				vb.gui = false
				vb.name = "k8s-node#{i}"
				vb.memory = "2048"
			end
			nodek8sconfig.vm.provision :shell, path: "provision/ubuntu_update.sh"
			nodek8sconfig.vm.provision :shell, path: "provision/java_install.sh"
			nodek8sconfig.vm.provision :shell, path: "provision/docker_install.sh"
			nodek8sconfig.vm.provision :shell, path: "provision/docker_compose_install.sh"
			nodek8sconfig.vm.provision :shell, path: "provision/kubeadm_install.sh"
			nodek8sconfig.vm.provision :shell, path: "provision/addons_install.sh"
			nodek8sconfig.vm.provision :shell, path: "provision/config_k8s_nodes.sh"
			nodek8sconfig.vm.provision :shell, path: "provision/kubeadm-node-init.sh"
		end
	end
end