apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    appe: postgres
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - args:
        - postgres
        - -c
        - max_connections=1000
        env:
        # Removed the creation of databases since those are going to be created during
        # the bootstrapping and migration phase.
        #- name: POSTGRES_MULTIPLE_DATABASES
        #  value: dataflow,db
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: postgres
        image: postgres:10.7-alpine
        name: postgres
        #volumeMounts:
        #  - name: postgres-volume
        #    mountPath: docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:10.7-alpine
        resources: {}
      restartPolicy: Always

      #volumes:
      #  - name: postgres-volume
      #    configMap:
      #      name: postgres-configmap
