apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "batch.fullname" . }}-migration-job
  labels:
    app: {{ template "batch.name" . }}
    component: migration
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "batch.name" . }}
        component: migration
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ template "batch.fullname" . }}-migration-job
        image: {{ .Values.migration.image }}:{{ .Values.migration.version }}
        imagePullPolicy: {{ .Values.migration.imagePullPolicy }}
        resources:
{{ toYaml .Values.migration.resources | indent 10 }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:{{ .Values.datasource.type }}://{{ template "batch.database" . }}:{{ .Values.datasource.port }}/{{ .Values.datasource.database }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.datasource.username }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "scdf.fullname" . }}
              key: database-password
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: {{ .Values.datasource.driverClassName }}
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
      initContainers:
      # Create databases if not exists. This initialization is specific only on postgres databases.
      # Use 'jdbc:mysql://dbhost:5432/db?createDatabaseIfNotExist=true' for other databases that supports this feature
      - name: init-db-wait
        image: busybox
        command: ['sh', '-c', 'until nc -w3 -z {{ template "batch.database" . }} {{ .Values.datasource.port }}; do echo waiting for database; sleep 3; done;']
      - name: init-create-dataflow
        image: postgres:10.7-alpine
        command: ['sh', '-c',
            'PGPASSWORD={{ .Values.datasource.password }} createuser -h {{ template "batch.database" . }} -p {{ .Values.datasource.port }} -U {{ .Values.datasource.username }} {{ .Values.datasource.database }};
            PGPASSWORD={{ .Values.datasource.password }} createdb -h {{ template "batch.database" . }} -p {{ .Values.datasource.port }} -O {{ .Values.datasource.username }} -U {{ .Values.datasource.username }} {{ .Values.datasource.database }};
            echo 0']
      restartPolicy: Never

