version: '3.5'

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: dataflow,db,oschestrator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/files:/docker-entrypoint-initdb.d
    networks:
      - dataflow-network

  minio:
    image: minio/minio:RELEASE.2019-03-27T22-35-21Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
    ports:
      - 9000:9000
    networks:
      - dataflow-network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! nc -z minio 9000; do echo 'Wait minio to startup...'; sleep 0.1; done;
      sleep 5;
      /usr/bin/mc config host add data http://minio:9000 minio password;
      /usr/bin/mc rm -r --force data/dataflow-bucket;
      /usr/bin/mc mb data/dataflow-bucket;
      /usr/bin/mc policy download data/dataflow-bucket;
      ls -la /sample-data;
      /usr/bin/mc cp /sample-data/sample-data.zip data/dataflow-bucket;
      /usr/bin/mc cp /sample-data/sample-data-prod.zip data/dataflow-bucket;
      exit 0;
      "
    volumes:
      - ${PWD}/files/:/sample-data/
    networks:
      - dataflow-network

  rest-service:
    image: jsa4000/dataflow-rest-service
    ports:
      - 8080:8080
    networks:
      - dataflow-network

  db-migration:
    image: jsa4000/dataflow-db-migration
    depends_on:
      - createbuckets
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - dataflow-network

  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server:2.0.1.RELEASE
    container_name: dataflow-server
    ports:
      - 9393:9393
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/dataflow
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.cloud.dataflow.server.uri=http://dockerhost:9393
      - spring.cloud.dataflow.features.streams-enabled=false
      - spring.cloud.dataflow.features.analytics-enabled=false
    depends_on:
      - db-migration
    volumes:
      - ${HOME}/.m2/repository/:/root/.m2/repository/
      - /tmp/:/tmp/
    networks:
      - dataflow-network

  scdf-db-migration:
    image: postgres:10.7-alpine
    depends_on:
      - dataflow-server
    entrypoint: >
      /bin/sh -c "
      while ! nc -z dataflow-server 9393; do echo 'Wait dataflow-server to startup...'; sleep 1; done;
      sleep 5;
      PGPASSWORD=password psql -h postgres -p 5432 -U postgres -d dataflow -c 'ALTER TABLE batch_job_execution_params ALTER COLUMN string_val TYPE VARCHAR(1024)';
      exit 0;
      "
    networks:
      - dataflow-network

networks:
  dataflow-network:
    name: dataflow-network