zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  extraInitContainers: |
    - name: init-exporters-hazelcast
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget --no-check-certificate https://repo1.maven.org/maven2/io/zeebe/hazelcast/zeebe-hazelcast-exporter/0.9.1/zeebe-hazelcast-exporter-0.9.1-jar-with-dependencies.jar -O /exporters/zeebe-hazelcast-exporter.jar; ls -al']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/
  env:
    - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH
      value: exporters/zeebe-hazelcast-exporter.jar
    - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME
      value: io.zeebe.hazelcast.exporter.HazelcastExporter
    
  envTemplated: 
    ZEEBE_HAZELCAST_REMOTE_ADDRESS: "{{ .Release.Name }}-hazelcast"
  elasticsearch:
    imageTag: 6.8.5 
    replicas: 1
    minimumMasterNodes: 1
  # Permit co-located instances for solitary minikube virtual machines.
    antiAffinity: "soft"
    labels: { "app" : "zeebe" }
  
  # Shrink default JVM heap.
    esJavaOpts: "-Xmx128m -Xms128m"
  
  # Allocate smaller chunks of memory per pod.
    resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "1000m"
        memory: "512M"
  
  # Request smaller persistent volumes.
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 100M
    
operate:
  enabled: true
  
tasklist:
  enabled: true
    
zeeqs: 
  enabled: true
  hazelcast:
    cluster:
      memberCount: 1
  
