spring:
  application:
    name: zeebe-worker
  profiles:
    active: local

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: info,health

zeebe:
  client:
    worker.defaultName: ${spring.application.name}
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true
    job.timeout: 5000

logging:
  level:
    root: info
    org.springframework: warn
